apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c9jqy8iue-python
  janus-idp.io/tekton: c9jqy8iue-python
  backstage.io/kubernetes-id: c9jqy8iue-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: c9jqy8iue-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
