apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: c9jqy8iue-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c9jqy8iue-python 
  name: c9jqy8iue-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: c9jqy8iue-python
    weight: 100 
